name: image_picker_example
description: Demonstrates how to use the image_picker plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  video_player: 0.5.2
  flutter:
    sdk: flutter
  image_picker:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

